### PR TITLE
Update OpenMC paths

### PR DESCRIPTION
**Pull request by DanShort12**
OpenMC installs into /usr/local but we were looking in /opt/openmc, so change the OpenMC paths to be under /usr/local.
Also removes unused pugixml include.

### CODE REVIEW

**Comment by makeclean** [comment]
If you provide no prefix path then it goes to /usr/local is the install
path not in the cmake/FindOpenmc.cmake path in openmc?

**Comment by DanShort12** [comment]
That's right. If openmc is installed by using `sudo make install` then the files are under /usr/local. If a user doesn't have admin rights (and so have installed somewhere else) then I think they would need to edit CMakeLists.txt to point to their install location.

This PR looks to address an issue mentioned by @qingfengxia on #11, so perhaps he can comment on the exact nature of that issue and whether this resolves it?

**Comment by qingfengxia** [comment]
for the moment,  hardcode is fine,  as far as cmake report error if openmc is not on path.   

/usr/local is a system path, where /usr/local/include. is accessible without -I.            That is why previously we hardcoded to "/opt/openmc" it still works.   

How about,  assuming openmc is on PATH,  find_program() just as `which openmc` will give the full path of openmc, from that full path openmc_DIR can be retrieved.  Is there any  FindOpenMC.cmake anywhere? the problem it may not been installed to cmake mod path. 

in the long  term,  a detector,  or  FindOpenMC.cmake is needed for install to user place on Linux cluster.

**Comment by makeclean** [comment]
There is, when you install openmc, it provides one

**Comment by DanShort12** [comment]
Oh I see, I can get the OpenMC_DIR from the package, but it doesn't seem to populate the usual _LIBS, _INCLUDE_DIRS etc., which is why I thought it wasn't findable from cmake. Should be able to use that info to build a relative path from the OpenMC cmake module directory though.

**Comment by DanShort12** [comment]
Latest version should give a more general way of finding the OpenMC install. I've tried with the standard (no prefix install) and with an install specified into ~/.local and both now work for me.

**Comment by shimwell** [comment]
Sorry to be a pain is there any chance this PR can be redirect to the new repository

https://github.com/open-radiation-sources/parametric-plasma-source

@DanShort12

**Comment by DanShort12** [comment]
Superseded by open-radiation-sources/parametric-plasma-source#1

**Pull request closed without merging**
